import type { GetStaticProps, GetStaticPropsResult, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Character, GetCharactersResults} from '../types'


export const getStaticProps: GetStaticProps =async(context)=> {

  const res = await fetch(`https://rickandmortyapi.com/api/character`)
  const data : GetCharactersResults = await res.json()
  return {
    props: { 
      characters:data.results
     }, // will be passed to the page component as props
  }
}

const Home: NextPage<{characters: Character[]}> = ({ characters } ) => {
  return (
    <>
 
   
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       
      <h1>Character Details</h1>
      <ul className="character-info">
   {
         characters.map((c: Character)=>(
          <li key={c.id}> 
          
          <div className="box">
          <div>
          <img src={c.image}  width="100" height="100" />
            </div>
            <div className="char-info">
            <span>{c.name} </span>
            <span>{c.gender}</span>
            <span>{c.location.name}</span>
            <span>{c.status}</span>

              </div>
            </div>
          
          
          
          </li>
        ))
    }
   </ul>
      </main>

      <footer className={styles.footer}>
       This is footer
      </footer>
    </div>

    </>
  )
}

export default Home
